### ISSUE TITLE
Error while editing a file

### ISSUE THREAD

**Issue by dsego** [google/xi-mac#52]
Typing in text works for a while and then it stops responding. Latest master.
```
thread '<unnamed>' panicked at 'self must cover all 0-regions of other', src/libcore/option.rs:794
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
   1: std::panicking::default_hook::{{closure}}
   2: std::panicking::default_hook
   3: std::panicking::rust_panic_with_hook
   4: std::panicking::begin_panic
   5: std::panicking::begin_panic_fmt
   6: rust_begin_unwind
   7: core::panicking::panic_fmt
   8: core::option::expect_failed
   9: xi_rope::multiset::Subset::transform
  10: xi_rope::engine::Engine::gc
  11: <xi_core_lib::internal::editor::Editor<W>>::dec_revs_in_flight
  12: <xi_core_lib::internal::plugins::manager::PluginManager<W>>::update_plugins::{{closure}}
  13: <F as xi_rpc::Callback>::call
  14: xi_rpc::ResponseHandler::invoke
  15: <F as crossbeam::FnBox>::call_box
  16: __rust_maybe_catch_panic
  17: <F as alloc::boxed::FnBox<A>>::call_box
  18: std::sys::imp::thread::Thread::new::thread_start
  19: _pthread_body
  20: _pthread_start
send error on send_rpc_notification method update_spans: Broken pipe (os error 32)
send error on send_rpc_notification method update_spans: Broken pipe (os error 32)
send error on send_rpc_notification method update_spans: Broken pipe (os error 32)
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "PoisonError { inner: .. }"', src/libcore/result.rs:859
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
   1: std::panicking::default_hook::{{closure}}
   2: std::panicking::default_hook
   3: std::panicking::rust_panic_with_hook
   4: std::panicking::begin_panic
   5: std::panicking::begin_panic_fmt
   6: rust_begin_unwind
   7: core::panicking::panic_fmt
   8: core::result::unwrap_failed
   9: <xi_core_lib::internal::tabs::Documents<W>>::do_rpc
  10: <xi_core_lib::MainState<W> as xi_rpc::Handler<W>>::handle_notification
  11: xi_core::main
  12: __rust_maybe_catch_panic
  13: std::rt::lang_start
```

**Comment by cmyr** [comment]
Hmm that's interesting. I haven't seen this crash before. Were any plugins activated, besides the syntax coloring? Have you seen it more than once? @trishume might have a better idea of what's going on here, he rewrote this recently.

**Comment by trishume** [comment]
This is probably my fault, but I don't know why yet. I'll try to remember to debug this on Monday.

**Comment by dsego** [comment]
@cmyr Just syntax coloring is active. It predictably crashes after a minute or two, every time. So far it hasn't crashed on new buffers, only when editing an existing file.

**Comment by trishume** [comment]
Okay I figured out the cause of this bug, the `Engine::gc` method doesn't handle collecting revisions that aren't the oldest ones properly, which produces an invalid history which is caught by the dynamic checking on the next GC.

I'm not sure whether to fix the GC or just delete it, since I'm not sure if we need it anymore. I'll talk to @raphlinus about it later.

**Comment by cmyr** [comment]
@trishume sounds good, thanks for looking into this.

**Comment by trishume** [comment]
For now if you need a workaround you can set `MAX_UNDOS` to `1_000_000` in `editor.rs` to effectively disable the GC.

**Comment by cmyr** [comment]
@dsego Would you like to confirm that this has resolved your crash?

**Comment by dsego** [comment]
@cmyr Looking good 👍

**Comment by cmyr** [comment]
@dsego great, thanks! 😄
